permission:
    sbm:
      command:
        info: sbm.command.info
        game: sbm.command.game
        team: sbm.command.team
      allow:
        break-blocks: sbm.allow.break-blocks
        interact: sbm.allow.interact
        behold-gamemode: sbm.allow.behold-gamemode
gates-pos:
  plates:
    blue-a: "70, 0, 29; 69, 0, 29; 68, 0, 29"
    blue-b: "72, 0, 29; 73, 0, 29; 74, 0, 29"
  barriers:
    blue-a: "68, 1, 28; 69, 1, 28; 70, 1, 28; 68, 2, 28; 69, 2, 28; 70, 2, 28"
    blue-b: "72, 1, 28; 73, 1, 28; 74, 1, 28; 72, 2, 28; 73, 2, 28; 74, 2, 28"
  signs:
    blue-a: "68, 3, 28; 69, 3, 28; 70, 3, 28"
    blue-b: "72, 3, 28; 73, 3, 28; 74, 3, 28"