permission:
    sbm:
      command:
        info: sbm.command.info
        game: sbm.command.game
        team: sbm.command.team
        maps: sbm.command.maps
      allow:
        break-blocks: sbm.allow.break-blocks
        item-move: sbm.allow.item-move
        behold-gamemode: sbm.allow.behold-gamemode
gates-pos:
  plates:
    blue-a: "70, 0, 29; 69, 0, 29; 68, 0, 29"
    blue-b: "72, 0, 29; 73, 0, 29; 74, 0, 29"
  barriers:
    blue-a: "68, 1, 28; 69, 1, 28; 70, 1, 28; 68, 2, 28; 69, 2, 28; 70, 2, 28"
    blue-b: "72, 1, 28; 73, 1, 28; 74, 1, 28; 72, 2, 28; 73, 2, 28; 74, 2, 28"
  signs:
    blue-a: "68, 3, 28; 69, 3, 28; 70, 3, 28"
    blue-b: "72, 3, 28; 73, 3, 28; 74, 3, 28"
server-open-signs: "43, -5, 4; 43, -5, 6; -4, 1, 49; -45, 0, 8; -5, 1, -33; -13, 0, 6; -13, 0, 2"

spawn-points:
  respawn-points:
    team-blue: "85, -1, 17, -180, 0; 57, -1, 17, -180, 0; 71, -1, 7, -180, 0"
    team-red: "85, -1, -17; 57, -1, -17; 71, -1, -7"
    barrier: "55, 2, 0; 87, 0, 0"
  snowball:
    team-blue: "71, 0, 4; 71, 1, 4"
    team-red: "71, 0, -4; 71, 1, -4"
  winner: "71.5, 11, 0.5"
  forceload-chunks: "3,-2;3,-1;3,0;3,1;4,-2;4,-1;4,0;4,1;5,-2;5,-1;5,0;5,1"
  dead:
    team-blue: "71.5, 8, 47.5, -180, 0"
    team-red: "71.5, 8, -46.5"

rematch-spawn:
  team-blue: "71.5, 2, 3.5"
  team-red: "71.5, 2, -2.5"
  barrier-box: "97, 2, 8; 63, 4, -8"


arena-center: "71.5, 0, 0"

target:
  pos: "71, 1, 20; 71, 1, -20"
  circle: "71, 0, 18; 71, 0, -18"
  square: "77, 0, 16; 66, 7, 22; 77, 0, -16; 66, 7, -22"

maps:
  rematch: "63, 15, 140; 98, -1, 185"
  winner: "25, 15, 140; 60, -1, 185"
  game: "-13, 15, 140; 22, -1, 185"