main: de.dachente.sbm.main.Main
version: 1.1.0-SNAPSHOT
name: SBM-Plugin
author: Olvier Martin
api-version: '1.21'
description: A Minecraft plugin
commands:
  alert:
    description: Sende Infos.
    aliases:
      - announce
      - info
  game:
    description: Alles was mit dem Spiel zu tun hat.
  game-server:
    description: Joine auf den Event-Server.
    aliases:
      - event-server
      - server
      - event
  team:
    description: Füge/Entferne spieler zu Teams.
    aliases:
      - tm
  lobby:
    description: Teleportiere dich in die Lobby.
    aliases:
      - hub
      - spawn