main: de.dachente.sbm.main.Main
version: 1.1.0-SNAPSHOT
name: SBM-Plugin
author: Olvier Martin
api-version: '1.21'
description: A Minecraft plugin about a Snowballmatch
depend: [ProtocolLib]
commands:
  alert:
    description: Send Infos.
    aliases:
      - announce
      - info
  game:
    description: Everything about the game.
  game-server:
    description: Join the Event-Server.
    aliases:
      - event-server
      - server
      - event
  team:
    description: Add remove Players to Teams.
    aliases:
      - tm
  lobby:
    description: Join the Lobby.
    aliases:
      - hub
      - spawn
  maps:
    description: Manage the Arena Maps.